import {
  beasiswa,
  bidangKajian,
  timeline,
  capaianPembelajaran,
  dosen,
  faq,
  fasilitas,
  hero,
  jalurMasuk,
  kegiatanMahasiswa,
  kelompokMataKuliah,
  kontak,
  kurikulum,
  misi,
  mitra,
  pimpinan,
  prestasi,
  prodi,
  profilLulusan,
  prospekKarir,
  sejarah,
  sorotan,
  tujuan,
  visi,
} from "./prodi";
import type { WebsiteConfig } from "./schema";

/** Isi awal website sebelum admin menyimpan perubahan dari CMS. */
export const defaultWebsiteConfig: WebsiteConfig = {
  identity: {
    heroTitle: hero.title,
    heroDescription: hero.description,
    heroImage: hero.image,
    statement:
      "Program Studi Ekonomi Syariah mempelajari ekonomi dengan prinsip syariah: perbankan dan keuangan syariah, zakat dan wakaf, pasar modal syariah, hingga industri halal. Mahasiswa belajar langsung bersama bursa, perbankan, dan regulator mitra prodi.",
    tagline: prodi.tagline,
    degree: prodi.degree,
    totalCredits: prodi.totalCredits,
    normalDuration: prodi.normalDuration,
    maxSemesters: prodi.maxSemesters,
    prodiAccreditation: prodi.prodiAccreditation ?? "",
    universityAccreditation: prodi.universityAccreditation,
    universityAccreditationPeriod: prodi.universityAccreditationPeriod,
  },
  profil: { sejarah, visi, misi, tujuan },
  pimpinan: pimpinan.map((p) => ({ name: p.name, role: p.role, photo: null })),
  dosen: dosen.map((d) => ({
    name: d.name,
    role: d.role,
    photo: null,
    expertise: d.expertise,
  })),
  prestasi: prestasi.map((p) => ({
    name: p.name,
    achievement: p.achievement,
    group: p.group,
    photo: null,
  })),
  kegiatan: sorotan.map((k) => ({ ...k, image: null })),
  bidangKajian,
  kelompokMataKuliah,
  kurikulum,
  profilLulusan,
  capaianPembelajaran,
  prospekKarir,
  kegiatanMahasiswa,
  beasiswa,
  timeline,
  mitra,
  fasilitas: fasilitas.map((f) => ({ ...f, image: null })),
  jalurMasuk,
  unduhan: [
    {
      title: "Sertifikat Akreditasi UIN Sunan Gunung Djati Bandung 2024–2029",
      category: "Akreditasi",
      description: "Akreditasi institusi peringkat Unggul dari BAN-PT.",
      url: "https://ppg.uinsgd.ac.id/wp-content/uploads/2024/11/Sertifikat-Akreditasi-UIN-Bandung-2024-2029.pdf",
    },
  ],
  faq,
  kontak: {
    address: kontak.address,
    street: kontak.street,
    email: kontak.email,
    hours: kontak.hours,
    instagram: kontak.instagram,
    instagramHandle: kontak.instagramHandle,
    tiktok: kontak.tiktok,
    x: kontak.x,
    facebookName: "eksyar uin sgd",
    linktree: kontak.linktree,
    website: prodi.officialSite,
    pmbUrl: kontak.pmbUrl,
    mapsUrl: kontak.mapsUrl,
  },
};
