import {
  beasiswa,
  bidangKajian,
  timeline,
  capaianPembelajaran,
  dosen,
  faq,
  fasilitas,
  hero,
  jalurMasuk,
  kegiatanMahasiswa,
  kelompokMataKuliah,
  kontak,
  kurikulum,
  misi,
  mitra,
  pimpinan,
  prestasi,
  prodi,
  profilLulusan,
  prospekKarir,
  sejarah,
  sorotan,
  tujuan,
  visi,
} from "./prodi";
import type { WebsiteConfig } from "./schema";

/** Isi awal website sebelum admin menyimpan perubahan dari CMS. */
export const defaultWebsiteConfig: WebsiteConfig = {
  identity: {
    heroTitle: hero.title,
    heroDescription: hero.description,
    heroImage: hero.image,
    statement:
      "Program Studi Ekonomi Syariah mempelajari ekonomi dengan prinsip syariah: perbankan dan keuangan syariah, zakat dan wakaf, pasar modal syariah, hingga industri halal. Mahasiswa belajar langsung bersama bursa, perbankan, dan regulator mitra prodi.",
    tagline: prodi.tagline,
    degree: prodi.degree,
    totalCredits: prodi.totalCredits,
    normalDuration: prodi.normalDuration,
    maxSemesters: prodi.maxSemesters,
    prodiAccreditation: prodi.prodiAccreditation ?? "",
    universityAccreditation: prodi.universityAccreditation,
    universityAccreditationPeriod: prodi.universityAccreditationPeriod,
  },
  profil: { sejarah, visi, misi, tujuan },
  pimpinan: pimpinan.map((p) => ({ name: p.name, role: p.role, photo: null })),
  dosen: dosen.map((d) => ({
    name: d.name,
    role: d.role,
    photo: null,
    expertise: d.expertise,
  })),
  prestasi: prestasi.map((p) => ({
    name: p.name,
    achievement: p.achievement,
    group: p.group,
    photo: null,
  })),
  kegiatan: sorotan.map((k) => ({ ...k, image: null })),
  bidangKajian,
  kelompokMataKuliah,
  kurikulum,
  profilLulusan,
  capaianPembelajaran,
  prospekKarir,
  kegiatanMahasiswa,
  beasiswa,
  timeline,
  mitra,
  tendik: [],
  galeri: [],
  video: [],
  publikasi: [
    {
      title:
        "Pengaruh pengetahuan dan religiusitas terhadap niat usaha mikro dan kecil penerima program Sertifikasi Halal Gratis (SEHATI) 2025 di Jawa Barat",
      authors: "Evi Sopiah, dkk.",
      year: "",
      venue: "JEMSI (Jurnal Ekonomi, Manajemen, dan Akuntansi) Vol. 12 No. 2",
      type: "Artikel jurnal",
      url: "",
    },
    {
      title:
        "Pengaruh Diskon dan Voucher Terhadap Keputusan Konsumen untuk Melakukan Pembelian Produk Fashion di Market Place",
      authors: "Evi Sopiah, dkk.",
      year: "",
      venue: "",
      type: "Artikel jurnal",
      url: "",
    },
  ],
  jurnal: [
    {
      name: "Al-Muamalat: Jurnal Ekonomi Syariah",
      description:
        "Jurnal ilmiah bidang ekonomi Islam, keuangan Islam, inovasi bisnis Islam, dan hukum ekonomi Islam.",
      url: "https://journal.uinsgd.ac.id/index.php/mua",
    },
    {
      name: "LOBI: Jurnal Laboratorium FEBI",
      description:
        "Terbitan Laboratorium FEBI UIN SGD (Maret & September) yang memuat hasil kajian, penelitian, dan pengabdian di bidang ekonomi, manajemen, dan bisnis Islam.",
      url: "https://journal.uinsgd.ac.id/",
    },
    {
      name: "Rumah Jurnal UIN SGD",
      description:
        "Portal seluruh jurnal ilmiah UIN Sunan Gunung Djati Bandung.",
      url: "https://ejournal.uinsgd.ac.id/",
    },
  ],
  testimoni: [],
  mutu: {
    description:
      "Penjaminan mutu prodi mengikuti Sistem Penjaminan Mutu Internal (SPMI) UIN SGD. Visi, misi, dan kurikulum ditinjau berkala bersama asosiasi program studi, regulator, praktisi industri, alumni, dan mahasiswa.",
    surveiUrl: "",
    tracerUrl: "https://cdc.uinsgd.ac.id/tracer_study/",
    sebaranUrl: "https://cdc.uinsgd.ac.id/tracer_study/sebaran_alumni",
  },
  fasilitas: fasilitas.map((f) => ({ ...f, image: null })),
  jalurMasuk,
  unduhan: [
    {
      title: "Sertifikat Akreditasi UIN Sunan Gunung Djati Bandung 2024–2029",
      category: "Akreditasi",
      description: "Akreditasi institusi peringkat Unggul dari BAN-PT.",
      url: "https://ppg.uinsgd.ac.id/wp-content/uploads/2024/11/Sertifikat-Akreditasi-UIN-Bandung-2024-2029.pdf",
    },
  ],
  faq,
  kontak: {
    address: kontak.address,
    street: kontak.street,
    email: kontak.email,
    hours: kontak.hours,
    instagram: kontak.instagram,
    instagramHandle: kontak.instagramHandle,
    tiktok: kontak.tiktok,
    x: kontak.x,
    facebookName: "eksyar uin sgd",
    linktree: kontak.linktree,
    website: prodi.officialSite,
    pmbUrl: kontak.pmbUrl,
    mapsUrl: kontak.mapsUrl,
  },
};
